package hibernate.mapping;
// Generated Aug 14, 2020 2:46:58 PM by Hibernate Tools 4.3.1



/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private long userId;
     private long phone;
     private String userName;
     private String password;
     private boolean isBlocked;
     private Profile profile;

    public Accounts() {
    }

	
    public Accounts(long phone, String userName, String password, boolean isBlocked) {
        this.userId = userId;
        this.phone = phone;
        this.userName = userName;
        this.password = password;
        this.isBlocked = isBlocked;
    }
    public Accounts(long phone, String userName, String password, boolean isBlocked, Profile profile) {
       this.userId = userId;
       this.phone = phone;
       this.userName = userName;
       this.password = password;
       this.isBlocked = isBlocked;
       this.profile = profile;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getPhone() {
        return this.phone;
    }
    
    public void setPhone(long phone) {
        this.phone = phone;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isIsBlocked() {
        return this.isBlocked;
    }
    
    public void setIsBlocked(boolean isBlocked) {
        this.isBlocked = isBlocked;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }




}


