package hibernate.mapping;
// Generated Sep 5, 2020 1:21:38 PM by Hibernate Tools 4.3.1



/**
 * Activity generated by hbm2java
 */
public class Activity  implements java.io.Serializable {


     private long activityId;
     private Profile profile;
     private long ownerId;
     private Long objectId;
     private Long parentObjectId;
     private Long postId;
     private byte activityType;
     private byte categoryType;
     private boolean unread;
     private long creationTime;
     private String text;

    public Activity() {
    }

	
    public Activity(Profile profile, long ownerId, byte activityType, byte categoryType, boolean unread, long creationTime) {
        this.profile = profile;
        this.ownerId = ownerId;
        this.activityType = activityType;
        this.categoryType = categoryType;
        this.unread = unread;
        this.creationTime = creationTime;
    }
    public Activity(Profile profile, long ownerId, Long objectId, Long parentObjectId, Long postId, byte activityType, byte categoryType, boolean unread, long creationTime, String text) {
       this.profile = profile;
       this.ownerId = ownerId;
       this.objectId = objectId;
       this.parentObjectId = parentObjectId;
       this.postId = postId;
       this.activityType = activityType;
       this.categoryType = categoryType;
       this.unread = unread;
       this.creationTime = creationTime;
       this.text = text;
    }
   
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public long getOwnerId() {
        return this.ownerId;
    }
    
    public void setOwnerId(long ownerId) {
        this.ownerId = ownerId;
    }
    public Long getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }
    public Long getParentObjectId() {
        return this.parentObjectId;
    }
    
    public void setParentObjectId(Long parentObjectId) {
        this.parentObjectId = parentObjectId;
    }
    public Long getPostId() {
        return this.postId;
    }
    
    public void setPostId(Long postId) {
        this.postId = postId;
    }
    public byte getActivityType() {
        return this.activityType;
    }
    
    public void setActivityType(byte activityType) {
        this.activityType = activityType;
    }
    public byte getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(byte categoryType) {
        this.categoryType = categoryType;
    }
    public boolean isUnread() {
        return this.unread;
    }
    
    public void setUnread(boolean unread) {
        this.unread = unread;
    }
    public long getCreationTime() {
        return this.creationTime;
    }
    
    public void setCreationTime(long creationTime) {
        this.creationTime = creationTime;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


