package hibernate.mapping;
// Generated Nov 21, 2020 5:04:41 PM by Hibernate Tools 4.3.1



/**
 * CommentsRepliesLikesId generated by hbm2java
 */
public class CommentsRepliesLikesId  implements java.io.Serializable {


     private long replyId;
     private long userId;

    public CommentsRepliesLikesId() {
    }

    public CommentsRepliesLikesId(long replyId, long userId) {
       this.replyId = replyId;
       this.userId = userId;
    }
   
    public long getReplyId() {
        return this.replyId;
    }
    
    public void setReplyId(long replyId) {
        this.replyId = replyId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CommentsRepliesLikesId) ) return false;
		 CommentsRepliesLikesId castOther = ( CommentsRepliesLikesId ) other; 
         
		 return (this.getReplyId()==castOther.getReplyId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getReplyId();
         result = 37 * result + (int) this.getUserId();
         return result;
   }   


}


