package hibernate.mapping;
// Generated Aug 21, 2020 6:20:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private long commentId;
     private Post post;
     private Profile profile;
     private String comment;
     private long likes;
     private long replies;
     private long commentTime;
     private long activityId;
     private Set commentsReplieses = new HashSet(0);
     private Set commentsLikeses = new HashSet(0);

    public Comments() {
    }

	
    public Comments(Post post, Profile profile, String comment, long likes, long replies, long commentTime, long activityId) {
        this.commentId = commentId;
        this.post = post;
        this.profile = profile;
        this.comment = comment;
        this.likes = likes;
        this.replies = replies;
        this.commentTime = commentTime;
       this.activityId = activityId;
    }
    public Comments(Post post, Profile profile, String comment, long likes, long replies, long commentTime, long activityId, Set commentsReplieses, Set commentsLikeses) {
       this.commentId = commentId;
       this.post = post;
       this.profile = profile;
       this.comment = comment;
       this.likes = likes;
       this.replies = replies;
       this.commentTime = commentTime;
       this.activityId = activityId;
       this.commentsReplieses = commentsReplieses;
       this.commentsLikeses = commentsLikeses;
    }
   
    public long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public long getLikes() {
        return this.likes;
    }
    
    public void setLikes(long likes) {
        this.likes = likes;
    }
    public long getReplies() {
        return this.replies;
    }
    
    public void setReplies(long replies) {
        this.replies = replies;
    }
    public long getCommentTime() {
        return this.commentTime;
    }
    
    public void setCommentTime(long commentTime) {
        this.commentTime = commentTime;
    }
    public Set getCommentsReplieses() {
        return this.commentsReplieses;
    }
    
    public void setCommentsReplieses(Set commentsReplieses) {
        this.commentsReplieses = commentsReplieses;
    }
    public Set getCommentsLikeses() {
        return this.commentsLikeses;
    }
    
    public void setCommentsLikeses(Set commentsLikeses) {
        this.commentsLikeses = commentsLikeses;
    }
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }




}


