package hibernate.mapping;
// Generated Nov 21, 2020 5:04:41 PM by Hibernate Tools 4.3.1



/**
 * CommentsLikes generated by hbm2java
 */
public class CommentsLikes  implements java.io.Serializable {


     private CommentsLikesId id;
     private Comments comments;
     private long activityId;

    public CommentsLikes() {
    }

    public CommentsLikes(CommentsLikesId id, Comments comments, long activityId) {
       this.id = id;
       this.comments = comments;
       this.activityId = activityId;
    }
   
    public CommentsLikesId getId() {
        return this.id;
    }
    
    public void setId(CommentsLikesId id) {
        this.id = id;
    }
    public Comments getComments() {
        return this.comments;
    }
    
    public void setComments(Comments comments) {
        this.comments = comments;
    }
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }




}


