package hibernate.mapping;
// Generated Nov 21, 2020 5:04:41 PM by Hibernate Tools 4.3.1



/**
 * CommentsLikesId generated by hbm2java
 */
public class CommentsLikesId  implements java.io.Serializable {


     private long commentId;
     private long userId;

    public CommentsLikesId() {
    }

    public CommentsLikesId(long commentId, long userId) {
       this.commentId = commentId;
       this.userId = userId;
    }
   
    public long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CommentsLikesId) ) return false;
		 CommentsLikesId castOther = ( CommentsLikesId ) other; 
         
		 return (this.getCommentId()==castOther.getCommentId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCommentId();
         result = 37 * result + (int) this.getUserId();
         return result;
   }   


}


