package hibernate.mapping;
// Generated Nov 21, 2020 5:04:41 PM by Hibernate Tools 4.3.1



/**
 * CommentsRepliesLikes generated by hbm2java
 */
public class CommentsRepliesLikes  implements java.io.Serializable {


     private CommentsRepliesLikesId id;
     private CommentsReplies commentsReplies;
     private long activityId;

    public CommentsRepliesLikes() {
    }

    public CommentsRepliesLikes(CommentsRepliesLikesId id, CommentsReplies commentsReplies, long activityId) {
       this.id = id;
       this.commentsReplies = commentsReplies;
       this.activityId = activityId;
    }
   
    public CommentsRepliesLikesId getId() {
        return this.id;
    }
    
    public void setId(CommentsRepliesLikesId id) {
        this.id = id;
    }
    public CommentsReplies getCommentsReplies() {
        return this.commentsReplies;
    }
    
    public void setCommentsReplies(CommentsReplies commentsReplies) {
        this.commentsReplies = commentsReplies;
    }
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }




}


