package hibernate.mapping;
// Generated Sep 3, 2020 9:14:16 PM by Hibernate Tools 4.3.1



/**
 * FollowingFollowersId generated by hbm2java
 */
public class FollowingFollowersId  implements java.io.Serializable {


     private long userOne;
     private long userTwo;

    public FollowingFollowersId() {
    }

    public FollowingFollowersId(long userOne, long userTwo) {
       this.userOne = userOne;
       this.userTwo = userTwo;
    }
   
    public long getUserOne() {
        return this.userOne;
    }
    
    public void setUserOne(long userOne) {
        this.userOne = userOne;
    }
    public long getUserTwo() {
        return this.userTwo;
    }
    
    public void setUserTwo(long userTwo) {
        this.userTwo = userTwo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FollowingFollowersId) ) return false;
		 FollowingFollowersId castOther = ( FollowingFollowersId ) other; 
         
		 return (this.getUserOne()==castOther.getUserOne())
 && (this.getUserTwo()==castOther.getUserTwo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserOne();
         result = 37 * result + (int) this.getUserTwo();
         return result;
   }   


}


