package hibernate.mapping;
// Generated Sep 3, 2020 9:14:16 PM by Hibernate Tools 4.3.1



/**
 * FollowingFollowers generated by hbm2java
 */
public class FollowingFollowers  implements java.io.Serializable {


     private FollowingFollowersId id;
     private Profile profileByUserOne;
     private Profile profileByUserTwo;
     private long followTime;
     private long activityId;

    public FollowingFollowers() {
    }

    public FollowingFollowers(FollowingFollowersId id, Profile profileByUserOne, Profile profileByUserTwo, long followTime, long activityId) {
       this.id = id;
       this.profileByUserOne = profileByUserOne;
       this.profileByUserTwo = profileByUserTwo;
       this.followTime = followTime;
       this.activityId = activityId;
    }
   
    public FollowingFollowersId getId() {
        return this.id;
    }
    
    public void setId(FollowingFollowersId id) {
        this.id = id;
    }
    public Profile getProfileByUserOne() {
        return this.profileByUserOne;
    }
    
    public void setProfileByUserOne(Profile profileByUserOne) {
        this.profileByUserOne = profileByUserOne;
    }
    public Profile getProfileByUserTwo() {
        return this.profileByUserTwo;
    }
    
    public void setProfileByUserTwo(Profile profileByUserTwo) {
        this.profileByUserTwo = profileByUserTwo;
    }
    public long getFollowTime() {
        return this.followTime;
    }
    
    public void setFollowTime(long followTime) {
        this.followTime = followTime;
    }
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }




}


