package hibernate.mapping;
// Generated Nov 3, 2020 7:40:48 PM by Hibernate Tools 4.3.1



/**
 * Music generated by hbm2java
 */
public class Music  implements java.io.Serializable {


     private long musicId;
     private String musicKey;
     private String album;
     private String artist;
     private String coverImage;
     private Long originalUser;
     private int sourceType;

    public Music() {
    }

	
    public Music(String musicKey, int sourceType) {
        this.musicId = musicId;
        this.musicKey = musicKey;
        this.sourceType = sourceType;
    }
    public Music(String musicKey, int sourceType, Long originalUser) {
        this.musicId = musicId;
        this.musicKey = musicKey;
        this.sourceType = sourceType;
       this.originalUser = originalUser;
    }
    public Music(String musicKey, String album, String artist, String coverImage, Long originalUser, int sourceType) {
       this.musicId = musicId;
       this.musicKey = musicKey;
       this.album = album;
       this.artist = artist;
       this.coverImage = coverImage;
       this.originalUser = originalUser;
       this.sourceType = sourceType;
    }
   
    public long getMusicId() {
        return this.musicId;
    }
    
    public void setMusicId(long musicId) {
        this.musicId = musicId;
    }
    public String getMusicKey() {
        return this.musicKey;
    }
    
    public void setMusicKey(String musicKey) {
        this.musicKey = musicKey;
    }
    public String getAlbum() {
        return this.album;
    }
    
    public void setAlbum(String album) {
        this.album = album;
    }
    public String getArtist() {
        return this.artist;
    }
    
    public void setArtist(String artist) {
        this.artist = artist;
    }
    public String getCoverImage() {
        return this.coverImage;
    }
    
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }
    public Long getOriginalUser() {
        return this.originalUser;
    }
    
    public void setOriginalUser(Long originalUser) {
        this.originalUser = originalUser;
    }
    public int getSourceType() {
        return this.sourceType;
    }
    
    public void setSourceType(int sourceType) {
        this.sourceType = sourceType;
    }




}


