package hibernate.mapping;
// Generated Sep 1, 2020 9:18:07 AM by Hibernate Tools 4.3.1



/**
 * NotificationsToken generated by hbm2java
 */
public class NotificationsToken  implements java.io.Serializable {


     private String token;
     private long userId;

    public NotificationsToken() {
    }

    public NotificationsToken(String token, long userId) {
       this.token = token;
       this.userId = userId;
    }
   
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }




}


