package hibernate.mapping;
// Generated Aug 14, 2020 2:46:58 PM by Hibernate Tools 4.3.1



/**
 * Otp generated by hbm2java
 */
public class Otp  implements java.io.Serializable {


     private long phone;
     private int otp;
     private byte tries;
     private long timestmp;

    public Otp() {
    }

    public Otp(long phone, int otp, byte tries, long timestmp) {
       this.phone = phone;
       this.otp = otp;
       this.tries = tries;
       this.timestmp = timestmp;
    }
   
    public long getPhone() {
        return this.phone;
    }
    
    public void setPhone(long phone) {
        this.phone = phone;
    }
    public int getOtp() {
        return this.otp;
    }
    
    public void setOtp(int otp) {
        this.otp = otp;
    }
    public byte getTries() {
        return this.tries;
    }
    
    public void setTries(byte tries) {
        this.tries = tries;
    }
    public long getTimestmp() {
        return this.timestmp;
    }
    
    public void setTimestmp(long timestmp) {
        this.timestmp = timestmp;
    }




}


