package hibernate.mapping;
// Generated Nov 20, 2020 6:30:10 PM by Hibernate Tools 4.3.1



/**
 * PostLikes generated by hbm2java
 */
public class PostLikes  implements java.io.Serializable {


     private PostLikesId id;
     private Post post;
     private long activityId;

    public PostLikes() {
    }

    public PostLikes(PostLikesId id, Post post, long activityId) {
       this.id = id;
       this.post = post;
       this.activityId = activityId;
    }
   
    public PostLikesId getId() {
        return this.id;
    }
    
    public void setId(PostLikesId id) {
        this.id = id;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(long activityId) {
        this.activityId = activityId;
    }




}


