package hibernate.mapping;
// Generated Aug 14, 2020 2:46:58 PM by Hibernate Tools 4.3.1



/**
 * PostSaved generated by hbm2java
 */
public class PostSaved  implements java.io.Serializable {


     private long savedId;
     private Post post;
     private long userId;

    public PostSaved() {
    }

    public PostSaved(Post post, long userId) {
       this.savedId = savedId;
       this.post = post;
       this.userId = userId;
    }
   
    public long getSavedId() {
        return this.savedId;
    }
    
    public void setSavedId(long savedId) {
        this.savedId = savedId;
    }
    public Post getPost() {
        return this.post;
    }
    
    public void setPost(Post post) {
        this.post = post;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }




}


