package hibernate.mapping;
// Generated Aug 11, 2020 7:01:03 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private long postId;
     private Music music;
     private Profile profile;
     private String caption;
     private byte viewPrivacy;
     private boolean allowComments;
     private boolean allowDownloads;
     private String coverImage;
     private String mediaKey;
     private long mediaSize;
     private int height;
     private int width;
     private long duration;
     private long likes;
     private long comments;
     private long postTime;
     private Set postSaveds = new HashSet(0);
     private Set hashtagses = new HashSet(0);
     private Set postLikeses = new HashSet(0);
     private Set commentses = new HashSet(0);

    public Post() {
    }

	
    public Post(Music music, Profile profile, String caption, byte viewPrivacy, boolean allowComments, boolean allowDownloads, String coverImage, String mediaKey, long mediaSize, int height, int width, long duration, long likes, long comments, long postTime) {
        this.postId = postId;
        this.music = music;
        this.profile = profile;
        this.caption = caption;
        this.viewPrivacy = viewPrivacy;
        this.allowComments = allowComments;
        this.allowDownloads = allowDownloads;
        this.coverImage = coverImage;
       this.mediaKey = mediaKey;
       this.mediaSize = mediaSize;
        this.height = height;
        this.width = width;
        this.duration = duration;
        this.likes = likes;
        this.comments = comments;
        this.postTime = postTime;
    }
    public Post(Music music, Profile profile, String caption, byte viewPrivacy, boolean allowComments, boolean allowDownloads, String coverImage, String mediaKey, long mediaSize, int height, int width, long duration, long likes, long comments, long postTime, Set hashtagses) {
        this.postId = postId;
        this.music = music;
        this.profile = profile;
        this.caption = caption;
        this.viewPrivacy = viewPrivacy;
        this.allowComments = allowComments;
        this.allowDownloads = allowDownloads;
        this.coverImage = coverImage;
       this.mediaKey = mediaKey;
       this.mediaSize = mediaSize;
        this.height = height;
        this.width = width;
        this.duration = duration;
        this.likes = likes;
        this.comments = comments;
        this.postTime = postTime;
       this.hashtagses = hashtagses;
    }
    public Post(Music music, Profile profile, String caption, byte viewPrivacy, boolean allowComments, boolean allowDownloads, String coverImage, String mediaKey, long mediaSize, int height, int width, long duration, long likes, long comments, long postTime, Set postSaveds, Set hashtagses, Set postLikeses, Set commentses) {
       this.postId = postId;
       this.music = music;
       this.profile = profile;
       this.caption = caption;
       this.viewPrivacy = viewPrivacy;
       this.allowComments = allowComments;
       this.allowDownloads = allowDownloads;
       this.coverImage = coverImage;
       this.mediaKey = mediaKey;
       this.mediaSize = mediaSize;
       this.height = height;
       this.width = width;
       this.duration = duration;
       this.likes = likes;
       this.comments = comments;
       this.postTime = postTime;
       this.postSaveds = postSaveds;
       this.hashtagses = hashtagses;
       this.postLikeses = postLikeses;
       this.commentses = commentses;
    }
   
    public long getPostId() {
        return this.postId;
    }
    
    public void setPostId(long postId) {
        this.postId = postId;
    }
    public Music getMusic() {
        return this.music;
    }
    
    public void setMusic(Music music) {
        this.music = music;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getCaption() {
        return this.caption;
    }
    
    public void setCaption(String caption) {
        this.caption = caption;
    }
    public byte getViewPrivacy() {
        return this.viewPrivacy;
    }
    
    public void setViewPrivacy(byte viewPrivacy) {
        this.viewPrivacy = viewPrivacy;
    }
    public boolean isAllowComments() {
        return this.allowComments;
    }
    
    public void setAllowComments(boolean allowComments) {
        this.allowComments = allowComments;
    }
    public boolean isAllowDownloads() {
        return this.allowDownloads;
    }
    
    public void setAllowDownloads(boolean allowDownloads) {
        this.allowDownloads = allowDownloads;
    }
    public String getCoverImage() {
        return this.coverImage;
    }
    
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }
    public String getMediaKey() {
        return this.mediaKey;
    }
    
    public void setMediaKey(String mediaKey) {
        this.mediaKey = mediaKey;
    }
    public long getMediaSize() {
        return this.mediaSize;
    }
    
    public void setMediaSize(long mediaSize) {
        this.mediaSize = mediaSize;
    }
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }
    public long getDuration() {
        return this.duration;
    }
    
    public void setDuration(long duration) {
        this.duration = duration;
    }
    public long getLikes() {
        return this.likes;
    }
    
    public void setLikes(long likes) {
        this.likes = likes;
    }
    public long getComments() {
        return this.comments;
    }
    
    public void setComments(long comments) {
        this.comments = comments;
    }
    public long getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(long postTime) {
        this.postTime = postTime;
    }
    public Set getPostSaveds() {
        return this.postSaveds;
    }
    
    public void setPostSaveds(Set postSaveds) {
        this.postSaveds = postSaveds;
    }
    public Set getHashtagses() {
        return this.hashtagses;
    }
    
    public void setHashtagses(Set hashtagses) {
        this.hashtagses = hashtagses;
    }
    public Set getPostLikeses() {
        return this.postLikeses;
    }
    
    public void setPostLikeses(Set postLikeses) {
        this.postLikeses = postLikeses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


