package hibernate.mapping;
// Generated Aug 21, 2020 6:20:19 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Long userId;
     private Accounts accounts;
     private String fullName;
     private String profilePic;
     private byte gender;
     private String dob;
     private String bio;
     private long followers;
     private long following;
     private long likes;
     private boolean verified;
     private Set posts = new HashSet(0);
     private Set followingFollowersesForUserOne = new HashSet(0);
     private Set followingFollowersesForUserTwo = new HashSet(0);
     private Set commentses = new HashSet(0);

    public Profile() {
    }

	
    public Profile(Accounts accounts, String fullName, byte gender, long followers, long following, long likes, boolean verified) {
        this.accounts = accounts;
        this.fullName = fullName;
        this.gender = gender;
        this.followers = followers;
        this.following = following;
        this.likes = likes;
        this.verified = verified;
    }
    public Profile(Accounts accounts, String fullName, String profilePic, byte gender, String dob, String bio, long followers, long following, long likes, boolean verified, Set posts, Set followingFollowersesForUserOne, Set followingFollowersesForUserTwo, Set commentses) {
       this.accounts = accounts;
       this.fullName = fullName;
       this.profilePic = profilePic;
       this.gender = gender;
       this.dob = dob;
       this.bio = bio;
       this.followers = followers;
       this.following = following;
       this.likes = likes;
       this.verified = verified;
       this.posts = posts;
       this.followingFollowersesForUserOne = followingFollowersesForUserOne;
       this.followingFollowersesForUserTwo = followingFollowersesForUserTwo;
       this.commentses = commentses;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getProfilePic() {
        return this.profilePic;
    }
    
    public void setProfilePic(String profilePic) {
        this.profilePic = profilePic;
    }
    public byte getGender() {
        return this.gender;
    }
    
    public void setGender(byte gender) {
        this.gender = gender;
    }
    public String getDob() {
        return this.dob;
    }
    
    public void setDob(String dob) {
        this.dob = dob;
    }
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }
    public long getFollowers() {
        return this.followers;
    }
    
    public void setFollowers(long followers) {
        this.followers = followers;
    }
    public long getFollowing() {
        return this.following;
    }
    
    public void setFollowing(long following) {
        this.following = following;
    }
    public long getLikes() {
        return this.likes;
    }
    
    public void setLikes(long likes) {
        this.likes = likes;
    }
    public boolean isVerified() {
        return this.verified;
    }
    
    public void setVerified(boolean verified) {
        this.verified = verified;
    }
    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }
    public Set getFollowingFollowersesForUserOne() {
        return this.followingFollowersesForUserOne;
    }
    
    public void setFollowingFollowersesForUserOne(Set followingFollowersesForUserOne) {
        this.followingFollowersesForUserOne = followingFollowersesForUserOne;
    }
    public Set getFollowingFollowersesForUserTwo() {
        return this.followingFollowersesForUserTwo;
    }
    
    public void setFollowingFollowersesForUserTwo(Set followingFollowersesForUserTwo) {
        this.followingFollowersesForUserTwo = followingFollowersesForUserTwo;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }




}


