package hibernate.mapping;
// Generated Dec 9, 2020 12:02:26 AM by Hibernate Tools 4.3.1



/**
 * Records generated by hbm2java
 */
public class Records  implements java.io.Serializable {


     private long id;
     private String video;
     private String cover;
     private long timestmp;

    public Records() {
    }

    public Records(String video, String cover, long timestmp) {
       this.video = video;
       this.cover = cover;
       this.timestmp = timestmp;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getVideo() {
        return this.video;
    }
    
    public void setVideo(String video) {
        this.video = video;
    }
    public String getCover() {
        return this.cover;
    }
    
    public void setCover(String cover) {
        this.cover = cover;
    }
    public long getTimestmp() {
        return this.timestmp;
    }
    
    public void setTimestmp(long timestmp) {
        this.timestmp = timestmp;
    }




}


