package hibernate.mapping;
// Generated Aug 21, 2020 8:55:42 AM by Hibernate Tools 4.3.1



/**
 * Tokens generated by hbm2java
 */
public class Tokens  implements java.io.Serializable {


     private long userId;
     private String token;
     private long timestmp;

    public Tokens() {
    }

    public Tokens(long userId, String token, long timestmp) {
       this.userId = userId;
       this.token = token;
       this.timestmp = timestmp;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public long getTimestmp() {
        return this.timestmp;
    }
    
    public void setTimestmp(long timestmp) {
        this.timestmp = timestmp;
    }




}


