package hibernate.mapping;
// Generated Aug 14, 2020 2:46:58 PM by Hibernate Tools 4.3.1



/**
 * Validlogin generated by hbm2java
 */
public class Validlogin  implements java.io.Serializable {


     private long autoId;
     private long userId;
     private long loginTimestamp;
     private boolean loggedIn;
     private String abc;
     private String xyz;

    public Validlogin() {
    }

    public Validlogin(long userId, long loginTimestamp, boolean loggedIn, String abc, String xyz) {
       this.autoId = autoId;
       this.userId = userId;
       this.loginTimestamp = loginTimestamp;
       this.loggedIn = loggedIn;
       this.abc = abc;
       this.xyz = xyz;
    }
   
    public long getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(long autoId) {
        this.autoId = autoId;
    }
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getLoginTimestamp() {
        return this.loginTimestamp;
    }
    
    public void setLoginTimestamp(long loginTimestamp) {
        this.loginTimestamp = loginTimestamp;
    }
    public boolean isLoggedIn() {
        return this.loggedIn;
    }
    
    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }
    public String getAbc() {
        return this.abc;
    }
    
    public void setAbc(String abc) {
        this.abc = abc;
    }
    public String getXyz() {
        return this.xyz;
    }
    
    public void setXyz(String xyz) {
        this.xyz = xyz;
    }




}


